新規投稿機能の実装
ShunsukeNagashima/ask pull request #5
Opened 2021-12-06 12:03 UTC by ShunsukeNagashima

### 内容
・パッケージの追加
 - @metamask/detect-provider
 - web3
 - unstated-next（コンテナ作成用）
 - ts-generator
 - typechain
 - typechain-target-web3-v1（型安全にweb3を使用するためのライブラリ）
 

・web3管理用のコンテナ作成
・ウォレット接続用のボタンコンポーネント作成
・ウォレット接続用のhook作成
・ウォレット接続用のモーダル作成
・新規投稿用のロジック追加

色々甘いところもありますが、、レビューお願いします！

2021-12-11 04:36 UTC, shun0305 requested changes

2021-12-11 04:36 UTC, shun0305 commented on src/components/newPost/newPost.container.tsx
> +          parseInt(web3.utils.toWei(data.reward, 'ether')),
weiに変換してしまっているので、1を入力したら10000000000000000000になりエラーが出ます。contractの`incentive`の型uint256の最大値より低いですが、イーサリアム上では単なる数字ではなくbigNumberとして扱われます。(誤差が生じるため)。このドキュメントに詳しく書いてあります！
https://docs.ethers.io/v5/api/utils/bignumber/#BigNumber--notes-safenumbers

2021-12-11 04:36 UTC, shun0305 commented on src/components/newPost/newPost.container.tsx
> +  reward: string;
下を変えるのでnumberで良いかと！

2021-12-11 04:36 UTC, shun0305 commented on src/utils/contractHelper.ts
> +  console.log(process.env.NEXT_PUBLIC_CONTRACT_ADDRESS)
コントラクトアドレスはgithubに載せても問題ないので`/constants`とかに置いておいて良いと思います！こんな感じに
`type Env = {
  askV1ContractAddress: string;
};
const ENVS: Env = {
  askV1ContractAddress: "0xd545A66AAa9617Dc9964659C44196680D2967E5C",
};
export default ENVS;`

2021-12-11 04:36 UTC, shun0305 commented on src/utils/contractHelper.ts
> +export const createQuestion = async (web3: Web3, reward: number, contents: string | number[]) => {
`contents`はstringだけで良い？

2021-12-11 04:36 UTC, shun0305 commented on src/utils/contractHelper.ts
> +export const getQuestions = async (web3: Web3) => {
個人的にはコントラクトメソッド使う時に毎回`web3`を取得して渡してあげるのは面倒かなぁと思います。metamaskと繋がってるか確認しないとだからその方が良いのかな...
少し考えてみます！

2021-12-11 04:36 UTC, shun0305 commented on src/components/connectWalletModal/connectWalletModal.tsx
> +              icon="/assets/metamask-fox.svg"
`assets`がないかもです！

2021-12-11 04:36 UTC, shun0305 commented on src/components/newPost/newPost.container.tsx
> +    <Layout>
`Layout`が二重で出ちゃってます！

2021-12-17 16:12 UTC, ShunsukeNagashima commented
ご指摘事項修正させていただきました！
お手隙の際に際レビューお願いいたします！

2021-12-17 16:12 UTC, ShunsukeNagashima commented on src/utils/contractHelper.ts
> +export const getQuestions = async (web3: Web3) => {
こちらだけ一旦そのままにしてあります！

2021-12-20 15:46 UTC, shun0305 approved these changes
![LGTM](https://image.lgtmoon.dev/88280)

2021-12-29 12:36 UTC, merged